services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  customer-service:
    build: ./customer-service
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - mynetwork

  inventory-service:
    build: ./inventory-service
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - mynetwork
  billing-service:
    build: ./billing-service
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - mynetwork

  api-gateway:
    build: ./api-gateway
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8888:8888"
    networks:
      - mynetwork

  config-service:
    build: ./config-service
    depends_on:
      - discovery-service
    ports:
      - "9999:9999"
    networks:
      - mynetwork

networks:
  mynetwork: